version: 2.1
jobs:

  mdl:
    docker:
      - image: rsrchboy/mdl
    steps:
      - checkout
      - run: mdl .

  # replace this with Black
  # Until then, adding a flake8 rule to allow max line lengths of 88
  #flake8:
  #docker:
  #- image: python:2.7
  #steps:
  #- checkout
  #- run: pip install flake8
  #- run: flake8 ddldump/

  postgres:
    docker:
      - image: python:2.7.14-stretch
      - image: circleci/postgres:9.6.8-alpine
    steps:
      - checkout
      - run:
          name: Install postgresql-client
          command: |
            apt-get update
            apt-get -y install postgresql-client-9.6
      - run:
          name: install dockerize
          command: wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && rm dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz
          environment:
            DOCKERIZE_VERSION: v0.3.0
      - run:
          name: Wait for postgres to come up
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run:
          name: Load ddldump postgres schema
          command: psql -h 127.0.0.1 -U postgres < ddldump_postgres.sql
      - run:
          name: Install postgres driver for python
          command: pip install psycopg2
      - run:
          name: Package the repo into a wheel
          command: python setup.py bdist_wheel
      - run:
          name: Install the newly-packaged wheel
          command: pip install dist/*
      - run:
          name: Run ddldump againt the postgres dumpfile
          command: ddldump --diff=ddldump_postgres.sql postgresql://postgres:postgres@127.0.0.1:5432

  postgrespython3:
    docker:
      - image: ubuntu:19.04
      - image: circleci/postgres:9.6.8-alpine
    steps:
      - checkout
      - run: apt-get update && apt-get install -y python3-pip libpq-dev libmysqlclient-dev wget
      - run:
          name: Install postgresql-client
          command: |
            apt-get update
            apt-get -y install postgresql-client
      - run:
          name: install dockerize
          command: wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && rm dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz
          environment:
            DOCKERIZE_VERSION: v0.3.0
      - run:
          name: Wait for postgres to come up
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run:
          name: Load ddldump postgres schema
          command: psql -h 127.0.0.1 -U postgres < ddldump_postgres.sql
      - run:
          name: Install postgres driver for python
          command: pip3 install psycopg2
      - run:
          name: Package the repo into a wheel
          command: python3 setup.py bdist_wheel
      - run:
          name: Install the newly-packaged wheel
          command: pip3 install dist/*
      - run:
          name: Run ddldump againt the postgres dumpfile
          command: ddldump --diff=ddldump_postgres.sql postgresql://postgres:postgres@127.0.0.1:5432

  mysql:
    docker:
      - image: python:2.7.14-stretch
      - image: circleci/mysql:5.5 # 5.5 is the latest version of mysql-client available on stretch
    steps:
      - checkout
      - run:
          name: Install mysql-client
          command: |
            apt-get update
            apt-get -y install mysql-client
      - run:
          name: install dockerize
          command: wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && rm dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz
          environment:
            DOCKERIZE_VERSION: v0.3.0
      - run:
          name: Wait for mysql to come up
          command: dockerize -wait tcp://localhost:3306 -timeout 1m
      - run:
          name: Set up "ddldump" database
          command: mysql -h 127.0.0.1 -e 'CREATE DATABASE IF NOT EXISTS `ddldump`'
      - run:
          name: Load ddldump mysql schema (with foreign key checks disabled)
          command: ( echo "SET FOREIGN_KEY_CHECKS=0; "; cat ddldump_mysql.sql ) | mysql -h 127.0.0.1 ddldump
      - run:
          name: Install mysql driver for python
          command: pip install mysqlclient
      - run:
          name: Package the repo into a wheel
          command: python setup.py bdist_wheel
      - run:
          name: Install the newly-packaged wheel
          command: pip install dist/*
      - run:
          name: Run ddldump against the mysql dumpfile
          command: ddldump --diff=ddldump_mysql.sql mysql://:@127.0.0.1:3306/ddldump

  mysqlpython3:
    docker:
      - image: ubuntu:19.04
      - image: circleci/mysql:5.5 # 5.5 is the latest version of mysql-client available on stretch
    steps:
      - checkout
      - run: apt-get update && apt-get install -y python3-pip libpq-dev libmysqlclient-dev wget
      - run:
          name: Install mysql-client
          command: |
            apt-get update
            apt-get -y install mysql-client
      - run:
          name: install dockerize
          command: wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && rm dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz
          environment:
            DOCKERIZE_VERSION: v0.3.0
      - run:
          name: Wait for mysql to come up
          command: dockerize -wait tcp://localhost:3306 -timeout 1m
      - run:
          name: Set up "ddldump" database
          command: mysql -h 127.0.0.1 -e 'CREATE DATABASE IF NOT EXISTS `ddldump`'
      - run:
          name: Load ddldump mysql schema (with foreign key checks disabled)
          command: ( echo "SET FOREIGN_KEY_CHECKS=0; "; cat ddldump_mysql.sql ) | mysql -h 127.0.0.1 ddldump
      - run:
          name: Install mysql driver for python
          command: pip3 install mysqlclient
      - run:
          name: Package the repo into a wheel
          command: python3 setup.py bdist_wheel
      - run:
          name: Install the newly-packaged wheel
          command: pip3 install dist/*
      - run:
          name: Run ddldump against the mysql dumpfile
          command: ddldump --diff=ddldump_mysql.sql mysql://:@127.0.0.1:3306/ddldump

workflows:
  version: 2
  phaser:
    jobs:
      - mdl
      - flake8
      - postgres
      - postgrespython3
      - mysql
      - mysqlpython3
